# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Lists',
                'ordering': ('list',),
            },
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('order',), 'verbose_name_plural': '  Types'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='number',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='volume',
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/images/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='publications/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='file',
            field=models.FileField(upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='customlink',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(help_text='List of authors separated by commas or <i>and</i>.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='publication',
            name='book_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citekey',
            field=models.CharField(blank=True, help_text='BibTex citation key. Leave blank if unsure.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='code',
            field=models.URLField(blank=True, help_text='Link to page with code.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=128, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='external',
            field=models.BooleanField(default=False, help_text='If publication was written in another lab, mark as external.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, help_text='Only for a book.', max_length=32, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=models.CharField(blank=True, help_text='List of keywords separated by commas.', max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='owner',
            field=models.CharField(blank=True, default='admin', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Needs review'), (1, 'Reviewed and published'), (2, 'Removed')], default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, help_text='Link to PDF or journal page.', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='bibtex_types',
            field=models.CharField(default='article', help_text='Possible BibTex types, separated by comma.', max_length=256, verbose_name='BibTex types'),
        ),
        migrations.AlterField(
            model_name='type',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide publications from main view.'),
        ),
        migrations.AlterField(
            model_name='type',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='lists',
            field=models.ManyToManyField(blank=True, to='publications.List'),
        ),
    ]
