# Generated by Django 2.2.27 on 2022-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20220221_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='owner',
            field=models.CharField(blank=True, default='admin', max_length=64),
        ),
    ]
